#!/bin/bash

if [[ -z $IMAP_USER ]]
then
  echo "Missing environment variable: IMAP_USER"
  exit 1
fi

if [[ -z $IMAP_PASS ]]
then
  echo "Missing environment variable: IMAP_PASS"
  exit 1
fi

IMAP_HOST='imappro.zoho.com'
IMAP_PORT=993

echo "Searching..."

declare message_ids="$(
cat <<-EOF | openssl s_client -connect ${IMAP_HOST}:${IMAP_PORT} -crlf -ign_eof -quiet |& sed -n '/^\* SEARCH /{ s///; s/\r//; p; }'
. LOGIN ${IMAP_USER} ${IMAP_PASS}
. SELECT INBOX
. SEARCH HEADER Subject "Remittance Delivery"
. LOGOUT
EOF
)"

echo "Found: $message_ids"

for id in $message_ids
do
  echo "Downloading ${id}"
  cat <<-EOF | openssl s_client -connect ${IMAP_HOST}:${IMAP_PORT} -crlf -ign_eof -quiet 2>/dev/null | sed '/^\* /d; /^\. /d' >"./${id}.imap"
		. LOGIN ${IMAP_USER} ${IMAP_PASS}
		. SELECT INBOX
		. FETCH ${id} (INTERNALDATE BODY[])
		. LOGOUT
	EOF
done
